#!/bin/bash

python /media/nimashiri/SSD1/pytorch/test/test_expecttest.py
python /media/nimashiri/SSD1/pytorch/test/test_foreach.py
python /media/nimashiri/SSD1/pytorch/test/test_functional_autograd_benchmark.py
python /media/nimashiri/SSD1/pytorch/test/test_license.py
python /media/nimashiri/SSD1/pytorch/test/test_linalg.py
python /media/nimashiri/SSD1/pytorch/test/test_logging.py
python /media/nimashiri/SSD1/pytorch/test/test_metal.py
python /media/nimashiri/SSD1/pytorch/test/test_mkldnn.py
python /media/nimashiri/SSD1/pytorch/test/test_mobile_optimizer.py
python /media/nimashiri/SSD1/pytorch/test/test_multiprocessing.py
python /media/nimashiri/SSD1/pytorch/test/test_multiprocessing_spawn.py
python /media/nimashiri/SSD1/pytorch/test/test_namedtensor.py
python /media/nimashiri/SSD1/pytorch/test/test_namedtuple_return_api.py
python /media/nimashiri/SSD1/pytorch/test/test_native_functions.py
python /media/nimashiri/SSD1/pytorch/test/test_nn.py
python /media/nimashiri/SSD1/pytorch/test/test_numba_integration.py
python /media/nimashiri/SSD1/pytorch/test/test_numpy_interop.py
python /media/nimashiri/SSD1/pytorch/test/test_openmp.py
python /media/nimashiri/SSD1/pytorch/test/test_ops.py
python /media/nimashiri/SSD1/pytorch/test/test_optim.py
python /media/nimashiri/SSD1/pytorch/test/test_futures.py
python /media/nimashiri/SSD1/pytorch/test/test_fx.py
python /media/nimashiri/SSD1/pytorch/test/test_fx_experimental.py
python /media/nimashiri/SSD1/pytorch/test/test_indexing.py
python /media/nimashiri/SSD1/pytorch/test/test_jit.py
python /media/nimashiri/SSD1/pytorch/test/test_jit_cuda_fuser.py
python /media/nimashiri/SSD1/pytorch/test/test_jit_disabled.py
python /media/nimashiri/SSD1/pytorch/test/test_jit_fuser.py
python /media/nimashiri/SSD1/pytorch/test/test_jit_fuser_legacy.py
python /media/nimashiri/SSD1/pytorch/test/test_jit_fuser_te.py
python /media/nimashiri/SSD1/pytorch/test/test_jit_legacy.py
python /media/nimashiri/SSD1/pytorch/test/test_jit_profiling.py
python /media/nimashiri/SSD1/pytorch/test/test_jit_py3.py
python /media/nimashiri/SSD1/pytorch/test/test_jit_simple.py
python /media/nimashiri/SSD1/pytorch/test/test_jit_string.py
python /media/nimashiri/SSD1/pytorch/test/quantization/test_backward_compatibility.py
python /media/nimashiri/SSD1/pytorch/test/quantization/test_bias_correction.py
python /media/nimashiri/SSD1/pytorch/test/quantization/test_equalize.py
python /media/nimashiri/SSD1/pytorch/test/quantization/test_fusion_passes.py
python /media/nimashiri/SSD1/pytorch/test/quantization/test_numeric_suite.py
python /media/nimashiri/SSD1/pytorch/test/quantization/test_numeric_suite_fx.py
python /media/nimashiri/SSD1/pytorch/test/quantization/test_qat_module.py
python /media/nimashiri/SSD1/pytorch/test/quantization/test_quantize.py
python /media/nimashiri/SSD1/pytorch/test/quantization/test_quantized_functional.py
python /media/nimashiri/SSD1/pytorch/test/quantization/test_quantized_module.py
python /media/nimashiri/SSD1/pytorch/test/quantization/test_quantized_op.py
python /media/nimashiri/SSD1/pytorch/test/quantization/test_quantized_tensor.py
python /media/nimashiri/SSD1/pytorch/test/quantization/test_quantize_fx.py
python /media/nimashiri/SSD1/pytorch/test/quantization/test_quantize_jit.py
python /media/nimashiri/SSD1/pytorch/test/quantization/test_workflow_module.py
python /media/nimashiri/SSD1/pytorch/test/test_function_schema.py
python /media/nimashiri/SSD1/pytorch/test/test_kernel_launch_checks.py
python /media/nimashiri/SSD1/pytorch/test/test_op_aliases.py
python /media/nimashiri/SSD1/pytorch/test/test_tensor_creation_ops.py
python /media/nimashiri/SSD1/pytorch/test/test_overrides.py
python /media/nimashiri/SSD1/pytorch/test/test_package.py
python /media/nimashiri/SSD1/pytorch/test/test_profiler.py
python /media/nimashiri/SSD1/pytorch/test/test_pruning_op.py
python /media/nimashiri/SSD1/pytorch/test/test_pytree.py
python /media/nimashiri/SSD1/pytorch/test/test_quantization.py
python /media/nimashiri/SSD1/pytorch/test/test_reductions.py
python /media/nimashiri/SSD1/pytorch/test/test_serialization.py
python /media/nimashiri/SSD1/pytorch/test/test_shape_ops.py
python /media/nimashiri/SSD1/pytorch/test/test_show_pickle.py
python /media/nimashiri/SSD1/pytorch/test/test_sort_and_select.py
python /media/nimashiri/SSD1/pytorch/test/test_sparse.py
python /media/nimashiri/SSD1/pytorch/test/test_spectral_ops.py
python /media/nimashiri/SSD1/pytorch/test/test_static_runtime.py
python /media/nimashiri/SSD1/pytorch/test/test_tensorboard.py
python /media/nimashiri/SSD1/pytorch/test/test_tensorexpr.py
python /media/nimashiri/SSD1/pytorch/test/test_tensorexpr_pybind.py
python /media/nimashiri/SSD1/pytorch/test/test_testing.py
python /media/nimashiri/SSD1/pytorch/test/test_throughput_benchmark.py
python /media/nimashiri/SSD1/pytorch/test/test_torch.py
python /media/nimashiri/SSD1/pytorch/test/test_type_hints.py
python /media/nimashiri/SSD1/pytorch/test/test_type_info.py
python /media/nimashiri/SSD1/pytorch/test/test_type_promotion.py
python /media/nimashiri/SSD1/pytorch/test/test_unary_ufuncs.py
python /media/nimashiri/SSD1/pytorch/test/test_utils.py
python /media/nimashiri/SSD1/pytorch/test/test_view_ops.py
python /media/nimashiri/SSD1/pytorch/test/test_vmap.py
python /media/nimashiri/SSD1/pytorch/test/test_vulkan.py
python /media/nimashiri/SSD1/pytorch/test/test_xnnpack_integration.py
