#!/bin/bash

python /media/nimashiri/SSD1/pytorch/test/benchmark_utils/test_benchmark_utils.py
python /media/nimashiri/SSD1/pytorch/test/bottleneck_test/test_args.py
python /media/nimashiri/SSD1/pytorch/test/bottleneck_test/test_cuda.py
python /media/nimashiri/SSD1/pytorch/test/custom_backend/test_custom_backend.py
python /media/nimashiri/SSD1/pytorch/test/custom_operator/test_custom_classes.py
python /media/nimashiri/SSD1/pytorch/test/custom_operator/test_custom_ops.py
python /media/nimashiri/SSD1/pytorch/test/distributed/algorithms/ddp_comm_hooks/test_ddp_hooks.py
python /media/nimashiri/SSD1/pytorch/test/distributed/nn/jit/test_instantiator.py
python /media/nimashiri/SSD1/pytorch/test/distributed/optim/test_zero_redundancy_optimizer.py
python /media/nimashiri/SSD1/pytorch/test/distributed/pipeline/sync/skip/test_api.py
python /media/nimashiri/SSD1/pytorch/test/distributed/pipeline/sync/skip/test_gpipe.py
python /media/nimashiri/SSD1/pytorch/test/distributed/pipeline/sync/skip/test_inspect_skip_layout.py
python /media/nimashiri/SSD1/pytorch/test/distributed/pipeline/sync/skip/test_leak.py
python /media/nimashiri/SSD1/pytorch/test/distributed/pipeline/sync/skip/test_portal.py
python /media/nimashiri/SSD1/pytorch/test/distributed/pipeline/sync/skip/test_stash_pop.py
python /media/nimashiri/SSD1/pytorch/test/distributed/pipeline/sync/skip/test_tracker.py
python /media/nimashiri/SSD1/pytorch/test/distributed/pipeline/sync/skip/test_verify_skippables.py
python /media/nimashiri/SSD1/pytorch/test/distributed/pipeline/sync/test_balance.py
python /media/nimashiri/SSD1/pytorch/test/distributed/pipeline/sync/test_bugs.py
python /media/nimashiri/SSD1/pytorch/test/distributed/pipeline/sync/test_checkpoint.py
python /media/nimashiri/SSD1/pytorch/test/distributed/pipeline/sync/test_copy.py
python /media/nimashiri/SSD1/pytorch/test/distributed/pipeline/sync/test_deferred_batch_norm.py
python /media/nimashiri/SSD1/pytorch/test/distributed/pipeline/sync/test_dependency.py
python /media/nimashiri/SSD1/pytorch/test/distributed/pipeline/sync/test_inplace.py
python /media/nimashiri/SSD1/pytorch/test/distributed/pipeline/sync/test_microbatch.py
python /media/nimashiri/SSD1/pytorch/test/distributed/pipeline/sync/test_phony.py
python /media/nimashiri/SSD1/pytorch/test/distributed/pipeline/sync/test_pipe.py
python /media/nimashiri/SSD1/pytorch/test/distributed/pipeline/sync/test_pipeline.py
python /media/nimashiri/SSD1/pytorch/test/distributed/pipeline/sync/test_stream.py
python /media/nimashiri/SSD1/pytorch/test/distributed/pipeline/sync/test_transparency.py
python /media/nimashiri/SSD1/pytorch/test/distributed/pipeline/sync/test_worker.py
python /media/nimashiri/SSD1/pytorch/test/distributed/rpc/test_faulty_agent.py
python /media/nimashiri/SSD1/pytorch/test/distributed/rpc/test_process_group_agent.py
python /media/nimashiri/SSD1/pytorch/test/distributed/rpc/test_tensorpipe_agent.py
python /media/nimashiri/SSD1/pytorch/test/distributed/test_c10d.py
python /media/nimashiri/SSD1/pytorch/test/distributed/test_c10d_spawn.py
python /media/nimashiri/SSD1/pytorch/test/distributed/test_data_parallel.py
python /media/nimashiri/SSD1/pytorch/test/distributed/test_distributed_fork.py
python /media/nimashiri/SSD1/pytorch/test/distributed/test_distributed_spawn.py
python /media/nimashiri/SSD1/pytorch/test/distributed/test_jit_c10d.py
python /media/nimashiri/SSD1/pytorch/test/distributed/test_nccl.py
python /media/nimashiri/SSD1/pytorch/test/distributions/test_constraints.py
python /media/nimashiri/SSD1/pytorch/test/distributions/test_distributions.py
python /media/nimashiri/SSD1/pytorch/test/distributions/test_transforms.py
python /media/nimashiri/SSD1/pytorch/test/distributions/test_utils.py
python /media/nimashiri/SSD1/pytorch/test/fx/test_fx_const_fold.py
python /media/nimashiri/SSD1/pytorch/test/fx/test_subgraph_rewriter.py
python /media/nimashiri/SSD1/pytorch/test/jit/test_async.py
python /media/nimashiri/SSD1/pytorch/test/jit/test_autodiff_subgraph_slicing.py
python /media/nimashiri/SSD1/pytorch/test/jit/test_backends.py
python /media/nimashiri/SSD1/pytorch/test/jit/test_builtins.py
python /media/nimashiri/SSD1/pytorch/test/jit/test_class_type.py
python /media/nimashiri/SSD1/pytorch/test/jit/test_complex.py
python /media/nimashiri/SSD1/pytorch/test/jit/test_complexity.py
python /media/nimashiri/SSD1/pytorch/test/jit/test_cuda.py
python /media/nimashiri/SSD1/pytorch/test/jit/test_custom_operators.py
python /media/nimashiri/SSD1/pytorch/test/jit/test_data_parallel.py
python /media/nimashiri/SSD1/pytorch/test/jit/test_enum.py
python /media/nimashiri/SSD1/pytorch/test/jit/test_export_modes.py
python /media/nimashiri/SSD1/pytorch/test/jit/test_freezing.py

