#!/bin/bash

python /media/nimashiri/SSD1/pytorch/test/jit/test_functional_blocks.py
python /media/nimashiri/SSD1/pytorch/test/jit/test_fuser_common.py
python /media/nimashiri/SSD1/pytorch/test/jit/test_hooks.py
python /media/nimashiri/SSD1/pytorch/test/jit/test_hooks_modules.py
python /media/nimashiri/SSD1/pytorch/test/jit/test_isinstance.py
python /media/nimashiri/SSD1/pytorch/test/jit/test_list_dict.py
python /media/nimashiri/SSD1/pytorch/test/jit/test_logging.py
python /media/nimashiri/SSD1/pytorch/test/jit/test_models.py
python /media/nimashiri/SSD1/pytorch/test/jit/test_module_containers.py
python /media/nimashiri/SSD1/pytorch/test/jit/test_module_interface.py
python /media/nimashiri/SSD1/pytorch/test/jit/test_onnx_export.py
python /media/nimashiri/SSD1/pytorch/test/jit/test_peephole.py
python /media/nimashiri/SSD1/pytorch/test/jit/test_profiler.py
python /media/nimashiri/SSD1/pytorch/test/jit/test_python_bindings.py
python /media/nimashiri/SSD1/pytorch/test/jit/test_python_ir.py
python /media/nimashiri/SSD1/pytorch/test/jit/test_recursive_script.py
python /media/nimashiri/SSD1/pytorch/test/jit/test_remove_mutation.py
python /media/nimashiri/SSD1/pytorch/test/jit/test_save_load.py
python /media/nimashiri/SSD1/pytorch/test/jit/test_slice.py
python /media/nimashiri/SSD1/pytorch/test/jit/test_string_formatting.py
python /media/nimashiri/SSD1/pytorch/test/jit/test_torchbind.py
python /media/nimashiri/SSD1/pytorch/test/jit/test_tracer.py
python /media/nimashiri/SSD1/pytorch/test/jit/test_type_sharing.py
python /media/nimashiri/SSD1/pytorch/test/jit/test_unsupported_ops.py
python /media/nimashiri/SSD1/pytorch/test/jit/test_warn.py
python /media/nimashiri/SSD1/pytorch/test/jit/test_with.py
python /media/nimashiri/SSD1/pytorch/test/jit/test_hash.py
python /media/nimashiri/SSD1/pytorch/test/mobile/test_lite_script_module.py
python /media/nimashiri/SSD1/pytorch/test/onnx/test_caffe2_common.py
python /media/nimashiri/SSD1/pytorch/test/onnx/test_custom_ops.py
python /media/nimashiri/SSD1/pytorch/test/onnx/test_models.py
python /media/nimashiri/SSD1/pytorch/test/onnx/test_models_onnxruntime.py
python /media/nimashiri/SSD1/pytorch/test/onnx/test_onnx_common.py
python /media/nimashiri/SSD1/pytorch/test/onnx/test_onnx_opset.py
python /media/nimashiri/SSD1/pytorch/test/onnx/test_operators.py
python /media/nimashiri/SSD1/pytorch/test/onnx/test_pytorch_common.py
python /media/nimashiri/SSD1/pytorch/test/onnx/test_pytorch_helper.py
python /media/nimashiri/SSD1/pytorch/test/onnx/test_pytorch_onnx_caffe2.py
python /media/nimashiri/SSD1/pytorch/test/onnx/test_pytorch_onnx_caffe2_quantized.py
python /media/nimashiri/SSD1/pytorch/test/onnx/test_pytorch_onnx_onnxruntime.py
python /media/nimashiri/SSD1/pytorch/test/onnx/test_pytorch_onnx_onnxruntime_cuda.py
python /media/nimashiri/SSD1/pytorch/test/onnx/test_pytorch_onnx_shape_inference.py
python /media/nimashiri/SSD1/pytorch/test/onnx/test_utility_funs.py
python /media/nimashiri/SSD1/pytorch/test/onnx/test_verify.py
python /media/nimashiri/SSD1/pytorch/test/print_test_stats.py
python /media/nimashiri/SSD1/pytorch/test/test_autograd.py
python /media/nimashiri/SSD1/pytorch/test/test_binary_ufuncs.py
python /media/nimashiri/SSD1/pytorch/test/test_bundled_images.py
python /media/nimashiri/SSD1/pytorch/test/test_bundled_inputs.py
python /media/nimashiri/SSD1/pytorch/test/test_complex.py
python /media/nimashiri/SSD1/pytorch/test/test_cpp_api_parity.py
python /media/nimashiri/SSD1/pytorch/test/test_cpp_extensions_aot.py
python /media/nimashiri/SSD1/pytorch/test/test_cpp_extensions_jit.py
python /media/nimashiri/SSD1/pytorch/test/test_cuda.py
python /media/nimashiri/SSD1/pytorch/test/test_cuda_primary_ctx.py
python /media/nimashiri/SSD1/pytorch/test/test_dataloader.py
python /media/nimashiri/SSD1/pytorch/test/test_datapipe.py
python /media/nimashiri/SSD1/pytorch/test/test_dataset.py
python /media/nimashiri/SSD1/pytorch/test/test_determination.py
python /media/nimashiri/SSD1/pytorch/test/test_dispatch.py
